"""Turn a recipe into a submission folder: one self-contained ``agent.py`` (plus a copy of the recipe).

The file is ``modular/core.py`` and the source of each atom the recipe uses, concatenated, with the recipe embedded: it
imports nothing from this repository, so it runs on the server and several of them can share one process.
"""

import ast
import json
import re
from pathlib import Path

import modular.atoms  # noqa: F401 - registers the atoms
from modular import core
from modular.core import ATOMS, RecipeError, validate_recipe


MARKER = "# generated by modular.build"
HERE = Path(__file__).resolve().parent
IMPORT = re.compile(r"^(import |from \S+ import )")


def load_recipe(path) -> dict:
    path = Path(path)
    try:
        return json.loads(path.read_text())
    except FileNotFoundError:
        raise RecipeError(f"{path}: no such recipe file") from None
    except json.JSONDecodeError as error:
        raise RecipeError(f"{path}: not valid JSON ({error})") from None


def _body(source: str, imports: set[str]) -> str:
    """The source minus its docstring, its ``build:strip`` lines and its top-level imports (put in ``imports``)."""
    lines = source.splitlines()
    tree = ast.parse(source)
    drop = set()
    if (
        tree.body
        and isinstance(tree.body[0], ast.Expr)
        and isinstance(getattr(tree.body[0], "value", None), ast.Constant)
    ):
        drop |= set(range(tree.body[0].lineno, tree.body[0].end_lineno + 1))
    kept = []
    for n, line in enumerate(lines, start=1):
        if n in drop or "build:strip" in line:
            continue
        if IMPORT.match(line):
            if line.rstrip().endswith("("):
                raise RecipeError("an atom's imports must fit on one line each")
            imports.add(line.strip())
            continue
        kept.append(line)
    return "\n".join(kept).strip("\n")


def render(recipe: dict) -> str:
    """The text of the generated agent.py for a (validated) recipe."""
    recipe = validate_recipe(recipe)
    imports = {"import json"}
    parts = [_body((HERE / "core.py").read_text(), imports)]
    for entry in recipe["atoms"]:
        cls = ATOMS[entry["atom"]]
        module = __import__(cls.__module__, fromlist=["x"])
        parts.append(_body(Path(module.__file__).read_text(), imports))
    doc = f'"""{recipe["name"]}: {recipe["description"] or "an agent built from atoms"}\n\n'
    doc += f"{MARKER} from a recipe; edit the recipe, not this file.\n"
    doc += f"Base: {recipe['base']}. Atoms, in the order applied:\n"
    doc += "".join(f"  {e['atom']} {e['params']}\n" for e in recipe["atoms"]) or "  (none)\n"
    doc += '"""\n'
    recipe_literal = "RECIPE = json.loads(r'''" + json.dumps(recipe, indent=2) + "''')"
    return doc + "\n" + "\n".join(sorted(imports)) + "\n\n\n" + "\n\n\n".join(parts) + "\n\n\n" + recipe_literal + "\n"


def write_agent(recipe: dict, folder, force: bool = False) -> str:
    """Write ``<folder>/agent.py`` and ``recipe.json`` for a recipe (a dict) and return the folder."""
    recipe = validate_recipe(recipe)
    folder = Path(folder)
    target = folder / "agent.py"
    if target.exists() and MARKER not in target.read_text() and not force:
        raise RecipeError(f"{target} exists and was not generated by modular.build; pass --force to overwrite it")
    folder.mkdir(parents=True, exist_ok=True)
    target.write_text(render(recipe))
    (folder / "recipe.json").write_text(json.dumps(recipe, indent=2) + "\n")
    return str(folder)


def build(recipe_path, out=None, force: bool = False) -> str:
    """Write ``<out>/agent.py`` (default ``agents/<recipe name>``) and return the folder."""
    recipe = validate_recipe(load_recipe(recipe_path))
    return write_agent(recipe, out or Path("agents") / recipe["name"], force)


__all__ = ["build", "write_agent", "render", "load_recipe", "core"]
